server:
  port: 8411

spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.temp.use_jdbc_metadata_defaults: false
  jersey:
    type: filter
  datasource:
    url: jdbc:postgresql://localhost:5432/audibene
    username: audibene_app
    password:
    hikari:
      connection-test-query: SELECT 1
      minimum-idle: 1
      maximum-pool-size: 10
  liquibase:
    change-log: classpath:liquibase/db.changelog.xml
    liquibase-schema: public
logging:
  level:
    com.idealo: DEBUG